<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\ADLM Rate Generator Plugin.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\defaultLabours.json" />
    <None Remove="Data\defaultMaterials.json" />
    <None Remove="Images\logoBlack.png" />
    <None Remove="Images\logoBlue.png" />
    <None Remove="Images\logoWhite.png" />
    <None Remove="Resources\adlm_badge.png" />
    <None Remove="Resources\adlm_rate_generator_logo.png" />
    <None Remove="Resources\adlm_rate_generator_logo_small.png" />
    <None Remove="Resources\adlm_studio_logo_small.png" />
    <None Remove="Resources\Backdrop.png" />
    <None Remove="Resources\bg_frame.png" />
    <None Remove="Resources\EUR.png" />
    <None Remove="Resources\GHS.png" />
    <None Remove="Resources\hex_big.png" />
    <None Remove="Resources\NGN.png" />
    <None Remove="Resources\panel_blueprint.png" />
    <None Remove="Resources\QAR.png" />
    <None Remove="Resources\user_avatar.jpg" />
    <None Remove="Resources\ZAR.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\defaultLabours.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\defaultMaterials.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\ADLM Rate Generator Plugin.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Images\logoBlack.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\logoBlue.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\logoWhite.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ADLMRate.ico" />
    <Resource Include="Resources\adlm_badge.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\adlm_rate_generator_logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\adlm_rate_generator_logo_small.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\adlm_studio_logo_small.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Backdrop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\banner_house.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\bg_frame.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\eur.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ghs.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\hex_big.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ngn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\panel_blueprint.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\qar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\usd.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\user_avatar.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\zar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="8.0.8" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.PixelartIcons" Version="5.1.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.RadixIcons" Version="5.1.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.SimpleIcons" Version="5.1.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="MongoDB.Driver" Version="3.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\ADLMRate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
