; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ADLM Rate Gen "
#define MyAppVersion "2.1"
#define MyAppPublisher "ADLM Studio"
#define MyAppURL "https://www.adlmstudios.net"
#define MyAppExeName "ADLMRateGen.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{94BBCB71-4002-453B-A64F-400EE2B2BBEE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\ADLM\OneDrive\Documentos\ADLM LICENSE FILE.txt
InfoBeforeFile=C:\Users\ADLM\OneDrive\Documentos\README.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\ADLM\OneDrive\Documentos\Installer        ; ← typo fixed\NOV 2025
OutputBaseFilename=ADLM Rate Gen
SetupIconFile=C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Resources\ADLM Rate Generator Plugin.ico
Password=[REDACTED-INSTALLER-PASSWORD]
Encryption=yes
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ADLMRateGen.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ADLMRateGen.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ADLMRateGen.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ADLMRateGen.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ADLMRateGen.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\app.config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ClosedXML.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ClosedXML.Parser.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\DnsClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\DocumentFormat.OpenXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\DocumentFormat.OpenXml.Framework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\EPPlus.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\EPPlus.Interfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ExcelNumberFormat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\FontAwesome.Sharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\labour.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.PixelartIcons.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.RadixIcons.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.SimpleIcons.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\materials.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Bcl.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.Configuration.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.Configuration.FileExtensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.Configuration.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.FileProviders.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.FileProviders.Physical.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.FileSystemGlobbing.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.IdentityModel.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.IdentityModel.JsonWebTokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.IdentityModel.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.IdentityModel.Tokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.IO.RecyclableMemoryStream.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Microsoft.Xaml.Behaviors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\MongoDB.Bson.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\MongoDB.Driver.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\RBush.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\SharpCompress.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\SixLabors.Fonts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Snappier.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\System.IdentityModel.Tokens.Jwt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\System.IO.Packaging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\System.Security.Cryptography.Pkcs.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\System.Security.Cryptography.Xml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\ZstdSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Data\defaultLabours.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Data\defaultMaterials.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Data\labour.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Data\materials.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Resources\ADLM Rate Generator Plugin.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Resources\ADLMRate.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\runtimes\win\lib\net8.0\System.Security.Cryptography.Pkcs.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\Data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

