; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ADLM Rate Gen "
#define MyAppVersion "2.2"
#define MyAppPublisher "ADLM Studio"
#define MyAppURL "https://www.adlmstudios.net"
#define MyAppExeName "ADLMRateGen.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

; ── Self-contained publish output (includes .NET runtime) ──
#define BuildOutput "C:\Users\ADLM\source\repos\ADLMRateGenPublicBuild\bin\Debug\net8.0-windows\win-x64"

; ── Shared ADLM env-var registration (reads ADLM_SHARED_* from the build
;    machine's environment at compile time; generates per-machine local
;    secrets at install time). ──
#include "..\ADLMInstallerScripts\AdlmEnvVars.iss"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{94BBCB71-4002-453B-A64F-400EE2B2BBEE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\ADLM\OneDrive\Documentos\ADLM LICENSE FILE.txt
InfoBeforeFile=C:\Users\ADLM\OneDrive\Documentos\README.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\ADLM\OneDrive\Documentos\Installer
OutputBaseFilename=ADLM Rate Gen
SetupIconFile={#BuildOutput}\Resources\ADLM Rate Generator Plugin.ico
; Installer password comes from the ADLM_INSTALLER_PASSWORD environment
; variable at compile time. Set it in the build machine/CI environment;
; never commit the actual password to source control. If unset, the
; installer is built without a password (Encryption falls back below).
#define InstallerPassword GetEnv("ADLM_INSTALLER_PASSWORD")
#if InstallerPassword != ""
Password={#InstallerPassword}
Encryption=yes
#endif
SolidCompression=yes
WizardStyle=modern
; Broadcasts WM_SETTINGCHANGE after install so our env vars become
; visible to Explorer and newly-launched processes without a reboot.
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; ── Ship the entire self-contained build (includes .NET runtime + all DLLs) ──
Source: "{#BuildOutput}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

; ── ADLM RateGen environment variables ────────────────────────────────────
; Shared secrets are read from the build-machine environment at compile time
; via the AdlmEnvVars.iss include. Uninstaller removes them so we don't
; leave live credentials in the registry after uninstall.
;
; Non-secret config:
Root: HKCU; Subkey: "Environment"; ValueType: string; ValueName: "ADLM_RATEGEN_API_BASE_URL"; ValueData: "{#AdlmApiBaseUrl}"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Environment"; ValueType: string; ValueName: "ADLM_RATEGEN_PRODUCT_KEY"; ValueData: "rategen"; Flags: uninsdeletevalue

; Shared secret: license JWT signing key (must match server's JWT_LICENSE_SECRET).
; Build fails loudly (empty string) if ADLM_SHARED_LICENSE_SECRET isn't set.
Root: HKCU; Subkey: "Environment"; ValueType: string; ValueName: "ADLM_RATEGEN_OFFLINE_LICENSE_SECRET"; ValueData: "{#AdlmSharedLicenseSecret}"; Flags: uninsdeletevalue; Check: AdlmCheckHasSharedLicenseSecret

; Shared secret: MongoDB connection string for the RateGen cluster.
Root: HKCU; Subkey: "Environment"; ValueType: string; ValueName: "ADLM_RATEGEN_MONGO_SRV"; ValueData: "{#AdlmSharedMongoSrv}"; Flags: uninsdeletevalue; Check: AdlmCheckHasSharedMongo

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
{ Guards — skip writing empty ADLM_* env vars when the build machine has
  not provided the matching secret. Avoids overwriting an existing value
  with blank during upgrade reinstalls. }
function AdlmCheckHasSharedLicenseSecret: Boolean;
begin
  Result := '{#AdlmSharedLicenseSecret}' <> '';
end;

function AdlmCheckHasSharedMongo: Boolean;
begin
  Result := '{#AdlmSharedMongoSrv}' <> '';
end;

{ Called by Inno Setup after files are installed. We generate the two
  per-machine local secrets here (so each user's machine gets unique
  values, never baked into the installer) and AdlmEnsureLocalSecret
  preserves any existing values on reinstall. }
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    { Local-only secrets — 32 random bytes (64 hex chars) is plenty. }
    AdlmEnsureLocalSecret('ADLM_RATEGEN_LOCAL_JWT_SECRET', 32);
    AdlmEnsureLocalSecret('ADLM_RATEGEN_ENCRYPTION_KEY', 32);
  end;
end;
