; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ADLM Rate Gen"
#define MyAppVersion "1.0"
#define MyAppPublisher "ADLM Studio"
#define MyAppURL "https://www.youtube.com/@ADLMStudio"
#define MyAppExeName "ADLMRateGen.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6AD41B4F-9E76-4048-AD69-3D5B29ACADD6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\user\Documents\ADLM RATE GEN APP END USER LICENSE AGREEMENT.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\user\source\Installers
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\user\source\repos\ADLMRateGen\Resources\ADLM Rate Generator Plugin.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\ADLMRateGen.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\ADLMRateGen.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\ADLMRateGen.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\ADLMRateGen.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\DnsClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\labour.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.PixelartIcons.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.RadixIcons.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\MahApps.Metro.IconPacks.SimpleIcons.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\materials.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Microsoft.Bcl.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Microsoft.IdentityModel.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Microsoft.IdentityModel.JsonWebTokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Microsoft.IdentityModel.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Microsoft.IdentityModel.Tokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\MongoDB.Bson.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\MongoDB.Driver.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\SharpCompress.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Snappier.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\System.IdentityModel.Tokens.Jwt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\ZstdSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\user\source\repos\ADLMRateGen\bin\Debug\net8.0-windows\Resources\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

